import type { Metadata } from 'next';
import { SignUp } from '@clerk/nextjs';

export const metadata: Metadata = {
  title: '',
  description: 'Generated by create next app',
};

const RegisterPage = () => {
  return <SignUp />;
};

export default RegisterPage;
