name: "📝 Documentation Update"
description: "Suggesting documentation changes"
title: "[DOCS]: "
labels: ["documentation", "enhancement"]
body:
  - type: markdown
    attributes:
      value: "Please provide the following details for the documentation update."

  - type: input
    id: section
    attributes:
      label: "Section to Update"
      description: "Which section of the documentation requires an update?"
    validations:
      required: true

  - type: textarea
    id: changes
    attributes:
      label: "Suggested Changes"
      description: "Describe the changes you want to propose."
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: "Reason for Update"
      description: "Why is this update necessary?"
    validations:
      required: true
