name: '🚨 Hotfix Request'
description: 'Template for requesting a hotfix'
title: '[HOTFIX]: <title>'
labels: ['bug', 'P1 - Critical']
body:
  - type: markdown
    attributes:
      value: 'Please provide the following details for the hotfix request.'

  - type: input
    id: description
    attributes:
      label: 'Issue Description'
      description: 'Describe the issue that needs an urgent fix.'

  - type: textarea
    id: impact
    attributes:
      label: 'Impact on Users'
      description: 'Describe how this issue impacts users.'
