name: '🧬 Refactor Request'
description: 'Template for suggesting code refactoring'
title: '[REFACTOR]: <title>'
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: 'Please provide the following details to propose refactoring.'

  - type: textarea
    id: current_code
    attributes:
      label: 'Current Code'
      description: 'Briefly describe or link to the code you think needs refactoring.'

  - type: textarea
    id: proposed_refactoring
    attributes:
      label: 'Proposed Refactoring'
      description: 'Describe how you would refactor the code.'

  - type: textarea
    id: benefits
    attributes:
      label: 'Benefits'
      description: 'Explain why refactoring is beneficial.'

  - type: dropdown
    id: priority
    attributes:
      label: 'Priority Level'
      description: 'Select how urgently the refactoring should be handled.'
      options:
        - Low
        - Moderate
        - High
        - Critical
