import type { Metadata } from 'next';
import { SignIn } from '@clerk/nextjs';

export const metadata: Metadata = {
  title: '',
  description: 'Generated by create next app',
};

const LoginPage = () => {
  return <SignIn />;
};

export default LoginPage;
