name: 'Auto Label Priority Level'
on:
  issues:
    types: [opened, edited]

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check Priority Level and Add Label
        uses: actions/github-script@v6
        with:
          script: |
            const priority = context.payload.issue.body.match(/Priority Level:\n\n- (Low|Moderate|High|Critical)/);
            if (priority) {
              const level = priority[1];
              let label;
              switch (level) {
                case 'Low':
                  label = 'P4 - Low';
                  break;
                case 'Moderate':
                  label = 'P3 - Medium';
                  break;
                case 'High':
                  label = 'P2 - High';
                  break;
                case 'Critical':
                  label = 'P1 - Critical';
                  break;
              }
              if (label) {
                await github.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.payload.issue.number,
                  labels: [label],
                });
              }
            }
